[custom]
;解决DNS泄露，无分流群组
ruleset=DIRECT,,[]DOMAIN-SUFFIX,DOMAIN-SUFFIX,ahcdn.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,sacdnssedge.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,live.mmcdn.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,surrit.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,rebang.today
ruleset=DIRECT,,[]DOMAIN-SUFFIX,xvideos-cdn.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,phncdn.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,noodlemagazine.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,jiuse701.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,pvvstream.pro
ruleset=DIRECT,,[]DOMAIN-SUFFIX,cdn.jsdelivr.net
ruleset=DIRECT,,[]DOMAIN-SUFFIX,xhcdn.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,mycdn.me
ruleset=DIRECT,,[]DOMAIN-SUFFIX,push.apple.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,mirrors.vsean.net
ruleset=DIRECT,,[]DOMAIN-KEYWORD,ksyuncdn
ruleset=DIRECT,,[]DOMAIN-KEYWORD,doppiocdn
ruleset=DIRECT,,[]DOMAIN,gdmf.apple.com
ruleset=DIRECT,,[]DOMAIN-SUFFIX,post.smzdm.com
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true
