#xhamster
DOMAIN-SUFFIX,xhcdn.com

#jabletv
DOMAIN-SUFFIX,mushroomtrack.com

#jiuse701
DOMAIN,cdn2.jiuse3.cloud

#91porn
DOMAIN-SUFFIX,btc760.com
DOMAIN-SUFFIX,btc620.com

#porntrex
DOMAIN-SUFFIX,cdntrex.com
DOMAIN-SUFFIX,pcdn.cloudswitches.com

#Xvideos
DOMAIN-SUFFIX,xvideos-cdn.com

#Pornhub
DOMAIN-SUFFIX,phncdn.com

#Noodlemagazine
DOMAIN-SUFFIX,noodlemagazine.com
DOMAIN-SUFFIX,pvvstream.pro

#Chaturbate
DOMAIN-SUFFIX,live.mmcdn.com

#missav
DOMAIN-SUFFIX,surrit.com

#stripchat
DOMAIN-KEYWORD,doppiocdn
